### ISSUE TITLE
Brug af `scanf_s`

### ISSUE THREAD

**Issue by audio-engineer** [audio-engineer/exercises#11]
@Danar435 Funktionen `scanf_s` findes kun på Windows, men ingen andre platformer. Derfor kan fx jeg ikke køre dit program på macOS.

![image](https://github.com/audio-engineer/exercises/assets/70742985/349ed2e4-e10c-4ff1-be45-2376331785f8)
https://github.com/audio-engineer/exercises/blob/e43fb7723ff4116d078493233267f37faf7b2de6/4_6/4_6_k/src/main.c#L9

Du kan løse problemet ved at gøre koden cross-platform ved at enten bruge `fgets` funktionen eller bruge platform macros. Læs evt. https://stackoverflow.com/questions/4605842/how-to-identify-platform-compiler-from-preprocessor-macros,
https://stackoverflow.com/questions/430424/are-there-any-macros-to-determine-if-my-code-is-being-compiled-to-windows og 
https://github.com/cpredef/predef/tree/master

**Comment by Danar435** [comment]
I'm aware, det fikser jeg senere
